"""
core/phases/phase1_spec_based.py
Spec-only Verilog-A / SystemVerilog generator (Phase 1).
"""
import os
import math
from typing import Tuple

# Behavioral-equation spec names this generator's hand-authored templates
# reference, mapped to known alternate names seen in real spec JSONs (e.g.
# configs/LDO_1V2.json uses "PSRR_at_1kHz"/"PSRR_at_1MHz"/"Output_Noise_RMS"
# rather than the built-in build_ldo_kg()'s "PSRR_1kHz"/"PSRR_1MHz"/
# "Output_Noise"). Tried in order after the canonical name before falling
# back to a hardcoded default, so naming drift doesn't silently substitute
# the wrong number.
SPEC_ALIASES = {
    'PSRR_1kHz': ['PSRR_at_1kHz'],
    'PSRR_1MHz': ['PSRR_at_1MHz'],
    'Output_Noise': ['Output_Noise_RMS'],
}


class Phase1SpecBasedGenerator:
    """Generate behavioural HDL from specKG alone — no simulation data required."""

    # Canonical circuit-role resolution rules, per IP type: ordered
    # (role, predicate) pairs matched against spec_kg.ports by metadata
    # (port_type/domain/fsm_role), not by literal name. This lets the
    # hand-authored analog equations below stay meaningful even when a
    # real spec JSON's port names differ from the toy vin/vout/gnd/en
    # template (e.g. LDO_1V2.json's VPWR/floop_out/EN_LDO/GND). Each role
    # claims the first unclaimed matching port in spec_kg.ports order, so
    # e.g. OTA's vinp/vinn (same predicate) resolve to distinct ports.
    _LDO_ROLES = [
        ('vin',   lambda p: p.port_type == 'supply'),
        ('gnd',   lambda p: p.port_type == 'ground'),
        ('en',    lambda p: p.fsm_role == 'enable' or p.port_type == 'enable'),
        ('vout',  lambda p: p.port_type == 'output' and p.domain == 'analog'),
        ('pok',   lambda p: p.fsm_role == 'ready'),
        ('fault', lambda p: p.fsm_role == 'fault'),
    ]
    _OTA_ROLES = [
        ('vinp',  lambda p: p.domain == 'analog' and p.port_type == 'input'),
        ('vinn',  lambda p: p.domain == 'analog' and p.port_type == 'input'),
        ('vout',  lambda p: p.port_type == 'output' and p.domain == 'analog'),
        ('vdd',   lambda p: p.port_type == 'supply'),
        ('vss',   lambda p: p.port_type == 'ground'),
        ('en',    lambda p: p.fsm_role == 'enable' or p.port_type == 'enable'),
    ]
    _DCDC_ROLES = [
        ('vin',   lambda p: p.port_type == 'supply'),
        ('vout',  lambda p: p.port_type == 'output' and p.domain == 'analog'),
        ('sw',    lambda p: p.fsm_role == 'mode' or
                            (p.port_type == 'output' and p.domain == 'mixed')),
        ('en',    lambda p: p.fsm_role == 'enable' or p.port_type == 'enable'),
        ('pg',    lambda p: p.fsm_role == 'ready'),
        ('gnd',   lambda p: p.port_type == 'ground'),
    ]
    _GENERIC_ROLES = [
        ('vin',  lambda p: p.port_type == 'supply'),
        ('vout', lambda p: p.port_type == 'output'),
        ('gnd',  lambda p: p.port_type == 'ground'),
    ]

    def __init__(self, spec_kg):
        self.spec_kg = spec_kg
        self.ip_type = spec_kg.ip_type.upper()

    # ─── Helpers ─────────────────────────────────────────────────────────────

    def _spec_by_name(self, name: str):
        for s in self.spec_kg.specs:
            if s.name == name:
                return s
        return None

    def _nominal(self, name: str, default: float = 0.0) -> float:
        s = self._spec_by_name(name)
        if s is None:
            for alias in SPEC_ALIASES.get(name, []):
                s = self._spec_by_name(alias)
                if s is not None:
                    break
        if s is None:
            print(f"[Phase1] WARNING: spec '{name}' not found in specKG "
                  f"(tried aliases {SPEC_ALIASES.get(name, [])}) — using "
                  f"hardcoded default {default}")
            return default
        return s.nominal

    def _min_val(self, name: str, default: float = 0.0) -> float:
        s = self._spec_by_name(name)
        return s.min_val if s else default

    def _max_val(self, name: str, default: float = 1e9) -> float:
        s = self._spec_by_name(name)
        return s.max_val if s else default

    # ─── Verilog-A generators ─────────────────────────────────────────────────

    def generate_veriloga(self, fsm_code: str = '') -> str:
        if self.ip_type == 'LDO':
            return self._va_ldo(fsm_code)
        elif self.ip_type == 'OTA':
            return self._va_ota(fsm_code)
        elif self.ip_type == 'DCDC':
            return self._va_dcdc(fsm_code)
        else:
            return self._va_generic(fsm_code)

    def _va_header(self, module_name: str, ports: list) -> list:
        lines = [
            f'// Auto-generated Verilog-A — {self.ip_type} Phase 1',
            '// Generated by surrogate_framework Phase1SpecBasedGenerator',
            '',
            '`include "disciplines.vams"',
            '`include "constants.vams"',
            '',
            f'module {module_name}(',
            '    ' + ', '.join(ports),
            ');',
            '',
        ]
        return lines

    def _va_spec_params(self) -> list:
        lines = ['    // Specification parameters']
        for s in self.spec_kg.specs:
            safe = s.name.replace(' ', '_').replace('.', '_')
            lines.append(
                f'    parameter real {safe}_nom = {s.nominal};'
                f'  // [{s.min_val}, {s.max_val}] {s.unit}'
            )
        lines.append('')
        return lines

    def _dynamic_ports(self, fallback: list) -> Tuple[list, list]:
        """Build the module port-id list and its electrical/direction
        declaration lines from spec_kg.ports, so the generated module's
        interface always matches whatever SpecKG was loaded (fixes Phase 1
        emitting a fixed 6-pin skeleton regardless of --spec_json). Uses
        the same port_direction causality rule the FSM codegen already
        uses (core.spec_kg.knowledge_graph.port_direction): explicit
        Port.direction wins, else output/status ⇒ output, supply/ground/
        bulk/inout ⇒ inout, else input. Falls back to a fixed literal port
        list only if spec_kg.ports is empty (should not happen for any
        real KG)."""
        from core.spec_kg.knowledge_graph import port_direction
        from core.fsm.fsm_codegen import _vid

        ports = list(getattr(self.spec_kg, 'ports', None) or [])
        if not ports:
            ids = list(fallback)
            return ids, [f'    electrical {", ".join(ids)};', '']

        dir_in, dir_out, dir_inout, all_ids = [], [], [], []
        for p in ports:
            ident = _vid(p.name)
            all_ids.append(ident)
            d = port_direction(p)
            if d == 'output':
                dir_out.append(ident)
            elif d == 'inout':
                dir_inout.append(ident)
            else:
                dir_in.append(ident)

        lines = [f'    electrical {", ".join(all_ids)};']
        if dir_in:
            lines.append(f'    input {", ".join(dir_in)};')
        if dir_out:
            lines.append(f'    output {", ".join(dir_out)};')
        if dir_inout:
            lines.append(f'    inout {", ".join(dir_inout)};')
        lines.append('')
        return all_ids, lines

    def _resolve_roles(self, role_rules: list) -> dict:
        """Resolve canonical circuit roles (vin/vout/gnd/en/...) to real
        SpecKG Port objects by metadata, not literal name (see the
        _*_ROLES tables above). Returns {role_name: Port|None}; a role is
        None only if spec_kg.ports has no port matching its predicate."""
        claimed = set()
        roles = {}
        for role_name, pred in role_rules:
            match = None
            for p in self.spec_kg.ports:
                if id(p) in claimed:
                    continue
                if pred(p):
                    match = p
                    break
            if match is not None:
                claimed.add(id(match))
            roles[role_name] = match
        return roles

    def _role_id(self, roles: dict, role_name: str, fallback: str) -> str:
        from core.fsm.fsm_codegen import _vid
        p = roles.get(role_name)
        return _vid(p.name) if p is not None else fallback

    def _va_ldo(self, fsm_code: str) -> str:
        vout_nom = self._nominal('Output_Voltage', 1.8)
        psrr_1k  = self._nominal('PSRR_1kHz', 80.0)
        psrr_1m  = self._nominal('PSRR_1MHz', 50.0)
        load_reg = self._nominal('Load_Regulation', 2.0)
        dropout  = self._nominal('Dropout_Voltage', 0.2)
        noise    = self._nominal('Output_Noise', 20.0)

        psrr_lin_1k = 10 ** (psrr_1k / 20.0)
        psrr_lin_1m = 10 ** (psrr_1m / 20.0)

        all_ids, port_decl_lines = self._dynamic_ports(
            ['vin', 'vout', 'gnd', 'en', 'pok', 'fault'])
        roles = self._resolve_roles(self._LDO_ROLES)
        vin  = self._role_id(roles, 'vin',  'vin')
        vout = self._role_id(roles, 'vout', 'vout')
        gnd  = self._role_id(roles, 'gnd',  'gnd')
        en   = self._role_id(roles, 'en',   'en')

        # FSM state parameter list from spec_kg.fsm_states (falls back to
        # this template's own canonical 6 states if the KG has none). Only
        # states this hand-authored template actually models get a guard/
        # equation arm below (matched case-insensitively); any other
        # custom state (e.g. UVLO/HIGH_POWER_MODE/SCAN_MODE/OVERRIDE) is
        # still declared as a valid enum value but falls through to the
        # `default` arm — Phase 1 is spec-only codegen and has no physics
        # model for states it wasn't given equations for.
        states = list(self.spec_kg.fsm_states) or \
            ['DISABLED', 'STARTUP', 'REGULATION', 'DROPOUT', 'FAULT', 'SHUTDOWN']

        def sid(*names):
            for n in names:
                for i, s in enumerate(states):
                    if s.upper() == n.upper():
                        return i
            return None

        from core.fsm.fsm_codegen import _vid
        disabled_s   = sid('DISABLED')
        startup_s    = sid('STARTUP')
        regulation_s = sid('REGULATION')
        dropout_s    = sid('DROPOUT')
        fault_s      = sid('FAULT_ST', 'FAULT')
        reset_s      = disabled_s if disabled_s is not None else 0

        def sname(i):
            return _vid(states[i])

        lines = self._va_header('ldo_model', all_ids)
        lines += port_decl_lines
        lines += self._va_spec_params()
        lines += [
            '    // Internal variables',
            '    real vout_ideal, psrr_effect_1k, psrr_effect_1m, load_reg_drop;',
            '    real vref;',
            '    integer current_state;',
            '',
            '    // FSM state parameters (from specKG.fsm_states)',
        ]
        for i, s in enumerate(states):
            lines.append(f'    parameter integer {_vid(s)} = {i};')
        lines += [
            '',
            '    analog begin',
            '',
            '        @(initial_step) begin',
            f'            current_state = {reset_s};',
            '            vref = 0.9;',
            '        end',
            '',
            '        // FSM transitions (hand-authored for the canonical LDO',
            '        // states this coarse spec-only template models)',
            '        case(current_state)',
        ]
        if disabled_s is not None and startup_s is not None:
            lines += [
                f'            {sname(disabled_s)}: begin',
                f'                if (V({en}) > 0.9) begin',
                f'                    @(cross(V({en}) - 0.9, +1))',
                f'                    current_state = {sname(startup_s)};',
                '                end',
                '            end',
            ]
        if startup_s is not None and regulation_s is not None:
            lines += [
                f'            {sname(startup_s)}: begin',
                f'                if (V({vout}) > 0.95 * Output_Voltage_nom) begin',
                f'                    @(cross(V({vout}) - 0.95*Output_Voltage_nom, +1))',
                f'                    current_state = {sname(regulation_s)};',
                '                end',
                '            end',
            ]
        if regulation_s is not None and dropout_s is not None:
            lines += [
                f'            {sname(regulation_s)}: begin',
                f'                if ((V({vin}) - V({vout})) < Dropout_Voltage_nom) begin',
                f'                    @(cross((V({vin})-V({vout})) - Dropout_Voltage_nom, -1))',
                f'                    current_state = {sname(dropout_s)};',
                '                end',
                '            end',
            ]
        if dropout_s is not None and regulation_s is not None:
            lines += [
                f'            {sname(dropout_s)}: begin',
                f'                if ((V({vin}) - V({vout})) > Dropout_Voltage_nom + 0.05) begin',
                f'                    @(cross((V({vin})-V({vout})) - Dropout_Voltage_nom - 0.05, +1))',
                f'                    current_state = {sname(regulation_s)};',
                '                end',
                '            end',
            ]
        if fault_s is not None and disabled_s is not None:
            lines += [
                f'            {sname(fault_s)}: begin',
                f'                if (V({en}) < 0.5) begin',
                f'                    @(cross(V({en}) - 0.5, -1))',
                f'                    current_state = {sname(disabled_s)};',
                '                end',
                '            end',
            ]
        lines += [
            '        endcase',
            '',
            '        // Ideal output from feedback equation: Vout = Vref*(1+Rf1/Rf2)',
            f'        vout_ideal = {vout_nom};  // = vref*(1+Rf1/Rf2)',
            '',
            '        // PSRR effect: ripple suppression',
            f'        psrr_effect_1k = (V({vin}) - {vout_nom + dropout:.4f}) / {psrr_lin_1k:.2f};',
            f'        psrr_effect_1m = (V({vin}) - {vout_nom + dropout:.4f}) / {psrr_lin_1m:.2f};',
            '',
            '        // Load regulation drop',
            f'        load_reg_drop = I({vout},{gnd}) * ({load_reg:.6f} / {vout_nom:.4f});',
            '',
            '        // Output voltage',
            '        case(current_state)',
        ]
        if disabled_s is not None:
            lines.append(f'            {sname(disabled_s)}: V({vout},{gnd}) <+ 0;')
        if startup_s is not None:
            lines.append(f'            {sname(startup_s)}:  V({vout},{gnd}) <+ vout_ideal * (1 - exp(-$abstime / 1e-6));')
        if regulation_s is not None:
            lines += [
                f'            {sname(regulation_s)}: begin',
                f'                V({vout},{gnd}) <+ vout_ideal + psrr_effect_1k - load_reg_drop;',
                '            end',
            ]
        if dropout_s is not None:
            lines += [
                f'            {sname(dropout_s)}: begin',
                f'                V({vout},{gnd}) <+ V({vin}) - Dropout_Voltage_nom;',
                '            end',
            ]
        if fault_s is not None:
            lines.append(f'            {sname(fault_s)}: V({vout},{gnd}) <+ 0;')
        lines += [
            f'            default:  V({vout},{gnd}) <+ 0;',
            '        endcase',
            '',
        ]
        if fsm_code:
            lines += ['        // --- Embedded FSM code ---', '        /*']
            lines += [f'        {l}' for l in fsm_code.split('\n')[:10]]
            lines += ['        */', '']
        lines += [
            '    end  // analog begin',
            '',
            'endmodule  // ldo_model',
        ]
        return '\n'.join(lines)

    def _va_ota(self, fsm_code: str) -> str:
        gbw      = self._nominal('GBW', 50.0) * 1e6
        pm       = self._nominal('Phase_Margin', 65.0)
        cmrr_db  = self._nominal('CMRR', 80.0)
        sr       = self._nominal('Slew_Rate', 50.0) * 1e6
        gm_nom   = self._nominal('Gm', 5.0) * 1e-3
        ro_nom   = self._nominal('Output_Resistance', 1000.0) * 1e3
        cl_nom   = gm_nom / (2 * math.pi * gbw) if gbw > 0 else 1e-12

        all_ids, port_decl_lines = self._dynamic_ports(
            ['vinp', 'vinn', 'vout', 'vdd', 'vss', 'en'])
        roles = self._resolve_roles(self._OTA_ROLES)
        vinp = self._role_id(roles, 'vinp', 'vinp')
        vinn = self._role_id(roles, 'vinn', 'vinn')
        vout = self._role_id(roles, 'vout', 'vout')
        vss  = self._role_id(roles, 'vss',  'vss')

        lines = self._va_header('ota_model', all_ids)
        lines += port_decl_lines
        lines += self._va_spec_params()
        lines += [
            f'    parameter real Gm_nom   = {gm_nom:.6g};   // A/V',
            f'    parameter real Ro_nom   = {ro_nom:.6g};   // Ohm',
            f'    parameter real CL_nom   = {cl_nom:.6g};   // F',
            '',
            '    real I_out, vdiff, vcm_feedthrough;',
            '    real fp2;',
            '',
            '    analog begin',
            '',
            '        @(initial_step) begin',
            f'            fp2 = {gbw * 5:.6g};  // non-dominant pole',
            '        end',
            '',
            f'        vdiff = V({vinp},{vinn});',
            '',
            '        // Gm stage: I_out = Gm*Vdiff - Vout/Ro',
            f'        I_out = Gm_nom * vdiff - V({vout},{vss}) / Ro_nom;',
            '',
            '        // Slew-rate limiting',
            f'        if (I_out > {sr * cl_nom:.6g})',
            f'            I_out = {sr * cl_nom:.6g};',
            f'        else if (I_out < -{sr * cl_nom:.6g})',
            f'            I_out = -{sr * cl_nom:.6g};',
            '',
            '        // CMRR feedthrough',
            f'        vcm_feedthrough = (V({vinp},{vss}) + V({vinn},{vss})) * 0.5 / pow(10, CMRR_nom/20.0);',
            '',
            '        // Output: laplace_nd for frequency response',
            f'        V({vout},{vss}) <+ laplace_nd(vdiff * Gm_nom * Ro_nom + vcm_feedthrough,',
            '                                   {1}, {1, 1/(2*`M_PI*fp2)});',
            '',
            '    end  // analog begin',
            '',
            'endmodule  // ota_model',
        ]
        return '\n'.join(lines)

    def _va_dcdc(self, fsm_code: str) -> str:
        vout_nom = self._nominal('Output_Voltage', 1.8)
        eff_nom  = self._nominal('Efficiency', 92.0) / 100.0

        all_ids, port_decl_lines = self._dynamic_ports(
            ['vin', 'vout', 'sw', 'en', 'pg', 'gnd'])
        roles = self._resolve_roles(self._DCDC_ROLES)
        vin  = self._role_id(roles, 'vin',  'vin')
        vout = self._role_id(roles, 'vout', 'vout')
        sw   = self._role_id(roles, 'sw',   'sw')
        gnd  = self._role_id(roles, 'gnd',  'gnd')

        lines = self._va_header('dcdc_model', all_ids)
        lines += port_decl_lines
        lines += self._va_spec_params()
        lines += [
            '    real duty_cycle, vout_ideal;',
            '',
            '    analog begin',
            '',
            '        // Ideal duty cycle (buck CCM): D = Vout/Vin',
            f'        duty_cycle = {vout_nom:.4f} / max(V({vin}), 0.001);',
            '',
            '        // Averaged output voltage',
            f'        vout_ideal = duty_cycle * V({vin}) * {eff_nom:.6f};  // efficiency',
            '',
            f'        V({vout},{gnd}) <+ vout_ideal;',
            '',
            '        // KVL: V_L = V_in - V_out during ton',
            f'        V({sw},{gnd}) <+ V({vin}) * (1 - duty_cycle);',
            '',
            '    end  // analog begin',
            '',
            'endmodule  // dcdc_model',
        ]
        return '\n'.join(lines)

    def _va_generic(self, fsm_code: str) -> str:
        all_ids, port_decl_lines = self._dynamic_ports(['vin', 'vout', 'gnd'])
        roles = self._resolve_roles(self._GENERIC_ROLES)
        vin  = self._role_id(roles, 'vin',  all_ids[0] if all_ids else 'vin')
        vout = self._role_id(roles, 'vout', all_ids[1] if len(all_ids) > 1 else 'vout')
        gnd  = self._role_id(roles, 'gnd',  all_ids[2] if len(all_ids) > 2 else 'gnd')

        lines = self._va_header(f'{self.ip_type.lower()}_model', all_ids)
        lines += port_decl_lines
        lines += self._va_spec_params()
        lines += [
            '    analog begin',
            f'        V({vout},{gnd}) <+ V({vin},{gnd});',
            '    end',
            'endmodule',
        ]
        return '\n'.join(lines)

    # ─── SystemVerilog generator ──────────────────────────────────────────────

    def generate_systemverilog(self) -> str:
        ip = self.ip_type.lower()
        states = self.spec_kg.fsm_states or ['IDLE', 'ACTIVE']
        n_bits = max(4, len(states).bit_length())

        lines = [
            f'// Auto-generated SystemVerilog — {self.ip_type} Phase 1',
            '// Generated by surrogate_framework Phase1SpecBasedGenerator',
            '',
            f'module {ip}_sv_model (',
            '    input  logic        clk,',
            '    input  logic        rst_n,',
            '    input  logic        en,',
            '    input  logic        fault_det,',
            '    input  logic        pok_det,',
            '    output logic        ready,',
            '    output logic        fault_out',
            ');',
            '',
        ]

        # Localparams from specs
        for s in self.spec_kg.specs:
            safe = s.name.replace(' ', '_').replace('.', '_')
            lines.append(f'    localparam real {safe}_nom = {s.nominal};  // {s.unit}')
        lines.append('')

        # Typedef enum
        lines.append(f'    typedef enum logic [{n_bits-1}:0] {{')
        for i, sname in enumerate(states):
            comma = ',' if i < len(states) - 1 else ''
            lines.append(f'        {sname}{comma}')
        lines.append('    } state_t;')
        lines.append('')
        lines.append('    state_t current_state, next_state;')
        lines.append('')

        # always_ff
        lines += [
            '    always_ff @(posedge clk or negedge rst_n) begin',
            '        if (!rst_n)',
            f'            current_state <= {states[0]};',
            '        else',
            '            current_state <= next_state;',
            '    end',
            '',
        ]

        # always_comb
        lines += [
            '    always_comb begin',
            '        next_state = current_state;',
            '        ready      = 1\'b0;',
            '        fault_out  = 1\'b0;',
            '',
            '        case (current_state)',
        ]

        for i, sname in enumerate(states):
            lines.append(f'            {sname}: begin')
            if 'REGULATION' in sname or 'ACTIVE' in sname or 'CCM' in sname or 'SETTLED' in sname:
                lines.append('                ready = 1\'b1;')
            if 'FAULT' in sname:
                lines.append('                fault_out = 1\'b1;')
            # Simple transition logic
            if i + 1 < len(states):
                lines.append(f'                if (en && !fault_det)')
                lines.append(f'                    next_state = {states[i+1]};')
            if 'REGULATION' in sname or 'ACTIVE' in sname or 'CCM' in sname:
                lines.append(f'                if (fault_det)')
                lines.append(f'                    next_state = {states[-2] if len(states) > 2 else states[0]};')
            lines.append('            end')

        lines += [
            f'            default: next_state = {states[0]};',
            '        endcase',
            '    end',
            '',
            f'endmodule  // {ip}_sv_model',
        ]

        return '\n'.join(lines)

    # ─── Generate all ─────────────────────────────────────────────────────────

    def generate_all(self, fsm_code: str = '',
                     output_dir: str = 'output') -> Tuple[str, str]:
        os.makedirs(output_dir, exist_ok=True)
        ip = self.ip_type.lower()

        va_code = self.generate_veriloga(fsm_code)
        sv_code = self.generate_systemverilog()

        va_path = os.path.join(output_dir, f'{ip}_phase1.vams')
        sv_path = os.path.join(output_dir, f'{ip}_phase1.sv')

        with open(va_path, 'w', encoding='utf-8') as f:
            f.write(va_code)
        with open(sv_path, 'w', encoding='utf-8') as f:
            f.write(sv_code)

        print(f"[Phase1] Verilog-A → {va_path}")
        print(f"[Phase1] SystemVerilog → {sv_path}")
        return va_path, sv_path
