// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : example_soc
// Generated: 2026-06-03 09:18
// Desc     : Feature: dma_transfer
// ============================================================================


// Feature Description: DMA channel data transfer feature — covers width, burst, direction, and address alignment
//
// Tags: dma, transfer, bus
// Source: specs/dma_spec_v2.1.pdf

// Feature: dma_transfer
// CoverGroups: data_width_cg, transfer_mode_cg, addr_alignment_cg

covergroup data_width_cg @(posedge clk) iff (dma_enable);  // Covers all legal DMA transfer widths
  option.goal = 100;

  width_cp : coverpoint dma_width {  // Transfer data width in bits
    bins BIN_8BIT = {8};
    bins BIN_16BIT = {16};
    bins BIN_32BIT = {32};
    bins BIN_64BIT = {64};
    bins BIN_128BIT = {128};
    illegal_bins BIN_ILLEGAL_WIDTH = {0, 1, 2, 4, 7, 9};
  }

  burst_len_cp : coverpoint dma_burst_len {  // Number of beats in a burst
    bins BIN_SINGLE = {1};
    bins BIN_SHORT = {[2:4]};
    bins BIN_MEDIUM = {[5:16]};
    bins BIN_LONG = {[17:256]};
    bins BIN_MAX = {256};
  }

  width_x_burst : cross width_cp, burst_len_cp {  // Cross width with burst length
  }
endgroup : data_width_cg

covergroup transfer_mode_cg @(posedge clk) iff (dma_enable);  // Transfer direction, mode, and address increment
  option.goal = 100;

  direction_cp : coverpoint dma_direction {
    bins BIN_MEM_TO_MEM = {0};
    bins BIN_MEM_TO_PERIPH = {1};
    bins BIN_PERIPH_TO_MEM = {2};
    bins BIN_PERIPH_TO_PERIPH = {3};
  }

  addr_increment_cp : coverpoint dma_addr_inc {
    bins BIN_FIXED = {0};
    bins BIN_INCREMENT = {1};
    bins BIN_DECREMENT = {2};
    bins BIN_AUTO = default;
  }

  state_cp : coverpoint dma_state {  // DMA state machine — state transitions
    bins BIN_IDLE_TO_ACTIVE = (IDLE => ACTIVE);
    bins BIN_ACTIVE_TO_DONE = (ACTIVE => DONE);
    bins BIN_ACTIVE_TO_ERROR = (ACTIVE => ERROR);
    bins BIN_FULL_TRANSFER = (IDLE => ACTIVE => DONE), (IDLE => ACTIVE => ACTIVE => DONE);
    bins BIN_ABORT_SEQ = (IDLE => ACTIVE => ERROR => IDLE);
  }
endgroup : transfer_mode_cg

covergroup addr_alignment_cg @(posedge clk) iff (dma_start);  // Source and destination address alignment
  option.goal = 100;

  src_align_cp : coverpoint dma_src_addr[2:0] {
    bins BIN_ALIGNED_8B = {0};
    bins BIN_UNALIGNED = {[1:7]};
    ignore_bins BIN_IGNORE_RSV = {8, 9, 10, 11, 12, 13, 14, 15};
  }

  dst_align_cp : coverpoint dma_dst_addr[2:0] {
    bins BIN_ALIGNED_8B = {0};
    bins BIN_UNALIGNED = {[1:7]};
  }

  addr_wildcard_cp : coverpoint dma_src_addr[7:0] {  // Wildcard-based address pattern coverage
    wildcard bins BIN_UPPER_HALF = {8'b1???????};
    wildcard bins BIN_LOWER_HALF = {8'b0???????};
  }
endgroup : addr_alignment_cg

// ---------------------------------------------------------------------------
// Instantiation template (copy to your testbench/class):
// ---------------------------------------------------------------------------
// data_width_cg dma_transfer_data_width_cg_inst;
// initial dma_transfer_data_width_cg_inst = new();
// // In your sample task:
// dma_transfer_data_width_cg_inst.sample();
//
// transfer_mode_cg dma_transfer_transfer_mode_cg_inst;
// initial dma_transfer_transfer_mode_cg_inst = new();
// // In your sample task:
// dma_transfer_transfer_mode_cg_inst.sample();
//
// addr_alignment_cg dma_transfer_addr_alignment_cg_inst;
// initial dma_transfer_addr_alignment_cg_inst = new();
// // In your sample task:
// dma_transfer_addr_alignment_cg_inst.sample();
//