// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : example_soc
// Generated: 2026-06-03 09:18
// Desc     : UVM Coverage Collector (skeleton)
// ============================================================================


`include "uvm_macros.svh"
import uvm_pkg::*;
import example_soc_fcov_pkg::*;

class example_soc_coverage extends uvm_subscriber #(/* transaction type */);
  `uvm_component_utils(example_soc_coverage)

  data_width_cg dma_transfer_data_width_cg_cov;
  transfer_mode_cg dma_transfer_transfer_mode_cg_cov;
  addr_alignment_cg dma_transfer_addr_alignment_cg_cov;
  priority_cg interrupt_handling_priority_cg_cov;
  mask_cg interrupt_handling_mask_cg_cov;
  nesting_cg interrupt_handling_nesting_cg_cov;
  power_state_cg power_management_power_state_cg_cov;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    dma_transfer_data_width_cg_cov = new();
    dma_transfer_transfer_mode_cg_cov = new();
    dma_transfer_addr_alignment_cg_cov = new();
    interrupt_handling_priority_cg_cov = new();
    interrupt_handling_mask_cg_cov = new();
    interrupt_handling_nesting_cg_cov = new();
    power_management_power_state_cg_cov = new();
  endfunction

  function void write(/* transaction type */ t);
    // TODO: unpack transaction fields into signals
    dma_transfer_data_width_cg_cov.sample();
    dma_transfer_transfer_mode_cg_cov.sample();
    dma_transfer_addr_alignment_cg_cov.sample();
    interrupt_handling_priority_cg_cov.sample();
    interrupt_handling_mask_cg_cov.sample();
    interrupt_handling_nesting_cg_cov.sample();
    power_management_power_state_cg_cov.sample();
  endfunction

endclass : example_soc_coverage