// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : example_soc
// Generated: 2026-06-03 09:18
// Desc     : Top-Level Coverage Package
// ============================================================================


package example_soc_fcov_pkg;

  `include "dma_transfer_coverage.sv"
  `include "interrupt_handling_coverage.sv"
  `include "power_management_coverage.sv"
  `include "example_soc_feature_crosses.sv"

endpackage : example_soc_fcov_pkg