// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : example_soc
// Generated: 2026-06-03 09:18
// Desc     : Feature-Level Cross Coverage (Synthesized)
// ============================================================================


// 4 feature cross(es) defined

// =============================================================
// FCovForge Synthesized Feature Cross: dma_width_x_irq_priority
// Verify DMA transfer width behavior under all interrupt priority levels
// Targets:
//   - dma_transfer.data_width_cg.width_cp
//   - interrupt_handling.priority_cg.priority_cp
// =============================================================

covergroup fcov_cross_dma_width_x_irq_priority_cg @(posedge clk);
  option.per_instance = 0;
  option.goal = 100;

  // Shadow of dma_transfer.data_width_cg.width_cp.width_cp
  shadow_dma_transfer_data_width_cg_width_cp_width_cp : coverpoint dma_width {
    bins BIN_8BIT = {8};
    bins BIN_16BIT = {16};
    bins BIN_32BIT = {32};
    bins BIN_64BIT = {64};
    bins BIN_128BIT = {128};
    illegal_bins BIN_ILLEGAL_WIDTH = {0, 1, 2, 4, 7, 9};
  }

  // Shadow of interrupt_handling.priority_cg.priority_cp.priority_cp
  shadow_interrupt_handling_priority_cg_priority_cp_priority_cp : coverpoint irq_priority {
    bins BIN_CRITICAL = {0};
    bins BIN_HIGH = {1, 2};
    bins BIN_MEDIUM = {[3:7]};
    bins BIN_LOW = {[8:15]};
    bins BIN_DEFAULT_PRIO = default;
  }

  // Feature-level cross
  dma_width_x_irq_priority_cross : cross shadow_dma_transfer_data_width_cg_width_cp_width_cp, shadow_interrupt_handling_priority_cg_priority_cp_priority_cp {
  }
endgroup : fcov_cross_dma_width_x_irq_priority_cg

// Instantiate in your testbench:
// fcov_cross_dma_width_x_irq_priority_cg dma_width_x_irq_priority_inst = new();
// dma_width_x_irq_priority_inst.sample();

// =============================================================
// FCovForge Synthesized Feature Cross: dma_mode_x_irq_nesting
// DMA transfer modes under nested interrupt scenarios
// Targets:
//   - dma_transfer.transfer_mode_cg
//   - interrupt_handling.nesting_cg
// =============================================================

covergroup fcov_cross_dma_mode_x_irq_nesting_cg @(posedge clk);
  option.per_instance = 0;
  option.goal = 90;

  // Shadow of dma_transfer.transfer_mode_cg.direction_cp
  shadow_dma_transfer_transfer_mode_cg_direction_cp : coverpoint dma_direction {
    bins BIN_MEM_TO_MEM = {0};
    bins BIN_MEM_TO_PERIPH = {1};
    bins BIN_PERIPH_TO_MEM = {2};
    bins BIN_PERIPH_TO_PERIPH = {3};
  }

  // Shadow of dma_transfer.transfer_mode_cg.addr_increment_cp
  shadow_dma_transfer_transfer_mode_cg_addr_increment_cp : coverpoint dma_addr_inc {
    bins BIN_FIXED = {0};
    bins BIN_INCREMENT = {1};
    bins BIN_DECREMENT = {2};
    bins BIN_AUTO = default;
  }

  // Shadow of dma_transfer.transfer_mode_cg.state_cp
  shadow_dma_transfer_transfer_mode_cg_state_cp : coverpoint dma_state {
    bins BIN_IDLE_TO_ACTIVE = (IDLE => ACTIVE);
    bins BIN_ACTIVE_TO_DONE = (ACTIVE => DONE);
    bins BIN_ACTIVE_TO_ERROR = (ACTIVE => ERROR);
    bins BIN_FULL_TRANSFER = (IDLE => ACTIVE => DONE), (IDLE => ACTIVE => ACTIVE => DONE);
    bins BIN_ABORT_SEQ = (IDLE => ACTIVE => ERROR => IDLE);
  }

  // Shadow of interrupt_handling.nesting_cg.nest_depth_cp
  shadow_interrupt_handling_nesting_cg_nest_depth_cp : coverpoint isr_nest_depth {
    bins BIN_DEPTH_0 = {0};
    bins BIN_DEPTH_1 = {1};
    bins BIN_DEPTH_2 = {2};
    bins BIN_DEPTH_3_PLUS = {[3:7]};
    bins BIN_OVERFLOW = {8};
    illegal_bins BIN_ILLEGAL_DEPTH = {[9:255]};
  }

  // Shadow of interrupt_handling.nesting_cg.nesting_state_cp
  shadow_interrupt_handling_nesting_cg_nesting_state_cp : coverpoint isr_state {
    bins BIN_PREEMPT = (ISR_ACTIVE => ISR_PREEMPT => ISR_RESUME);
    bins BIN_LATE_ARRIVAL = (ISR_ACTIVE => ISR_PENDING);
  }

  // Feature-level cross
  dma_mode_x_irq_nesting_cross : cross shadow_dma_transfer_transfer_mode_cg_direction_cp, shadow_dma_transfer_transfer_mode_cg_addr_increment_cp, shadow_dma_transfer_transfer_mode_cg_state_cp, shadow_interrupt_handling_nesting_cg_nest_depth_cp, shadow_interrupt_handling_nesting_cg_nesting_state_cp {
  }
endgroup : fcov_cross_dma_mode_x_irq_nesting_cg

// Instantiate in your testbench:
// fcov_cross_dma_mode_x_irq_nesting_cg dma_mode_x_irq_nesting_inst = new();
// dma_mode_x_irq_nesting_inst.sample();

// =============================================================
// FCovForge Synthesized Feature Cross: power_x_dma
// DMA transfer widths in different power states
// Targets:
//   - power_management.power_state_cg.pstate_cp
//   - dma_transfer.data_width_cg.width_cp
// =============================================================

covergroup fcov_cross_power_x_dma_cg @(posedge clk);
  option.per_instance = 0;
  option.goal = 85;

  // Shadow of power_management.power_state_cg.pstate_cp.pstate_cp
  shadow_power_management_power_state_cg_pstate_cp_pstate_cp : coverpoint power_state {
    bins BIN_ACTIVE = {0};
    bins BIN_IDLE = {1};
    bins BIN_SLEEP = {2};
    bins BIN_DEEP_SLEEP = {3};
    bins BIN_OFF = {4};
  }

  // Shadow of dma_transfer.data_width_cg.width_cp.width_cp
  shadow_dma_transfer_data_width_cg_width_cp_width_cp : coverpoint dma_width {
    bins BIN_8BIT = {8};
    bins BIN_16BIT = {16};
    bins BIN_32BIT = {32};
    bins BIN_64BIT = {64};
    bins BIN_128BIT = {128};
    illegal_bins BIN_ILLEGAL_WIDTH = {0, 1, 2, 4, 7, 9};
  }

  // Feature-level cross
  power_x_dma_cross : cross shadow_power_management_power_state_cg_pstate_cp_pstate_cp, shadow_dma_transfer_data_width_cg_width_cp_width_cp {
    ignore_bins excl = (binsof(shadow_power_management_power_state_cg_pstate_cp.BIN_OFF) && binsof(shadow_dma_transfer_data_width_cg_width_cp.BIN_64BIT));
  }
endgroup : fcov_cross_power_x_dma_cg

// Instantiate in your testbench:
// fcov_cross_power_x_dma_cg power_x_dma_inst = new();
// power_x_dma_inst.sample();

// =============================================================
// FCovForge Synthesized Feature Cross: dma_dir_x_irq_src_x_power
// Three-way cross: DMA direction, interrupt source, and power state
// Targets:
//   - dma_transfer.transfer_mode_cg.direction_cp
//   - interrupt_handling.priority_cg.source_cp
//   - power_management.power_state_cg.pstate_cp
// =============================================================

covergroup fcov_cross_dma_dir_x_irq_src_x_power_cg @(posedge clk);
  option.per_instance = 0;
  option.goal = 80;

  // Shadow of dma_transfer.transfer_mode_cg.direction_cp.direction_cp
  shadow_dma_transfer_transfer_mode_cg_direction_cp_direction_cp : coverpoint dma_direction {
    bins BIN_MEM_TO_MEM = {0};
    bins BIN_MEM_TO_PERIPH = {1};
    bins BIN_PERIPH_TO_MEM = {2};
    bins BIN_PERIPH_TO_PERIPH = {3};
  }

  // Shadow of interrupt_handling.priority_cg.source_cp.source_cp
  shadow_interrupt_handling_priority_cg_source_cp_source_cp : coverpoint irq_source {
    bins BIN_DMA_IRQ = {0, 1, 2, 3};
    bins BIN_UART_IRQ = {4, 5};
    bins BIN_SPI_IRQ = {6, 7};
    bins BIN_TIMER_IRQ = {8, 9, 10, 11};
    bins BIN_GPIO_IRQ = {[12:31]};
    ignore_bins BIN_RSVD = {[32:63]};
  }

  // Shadow of power_management.power_state_cg.pstate_cp.pstate_cp
  shadow_power_management_power_state_cg_pstate_cp_pstate_cp : coverpoint power_state {
    bins BIN_ACTIVE = {0};
    bins BIN_IDLE = {1};
    bins BIN_SLEEP = {2};
    bins BIN_DEEP_SLEEP = {3};
    bins BIN_OFF = {4};
  }

  // Feature-level cross
  dma_dir_x_irq_src_x_power_cross : cross shadow_dma_transfer_transfer_mode_cg_direction_cp_direction_cp, shadow_interrupt_handling_priority_cg_source_cp_source_cp, shadow_power_management_power_state_cg_pstate_cp_pstate_cp {
  }
endgroup : fcov_cross_dma_dir_x_irq_src_x_power_cg

// Instantiate in your testbench:
// fcov_cross_dma_dir_x_irq_src_x_power_cg dma_dir_x_irq_src_x_power_inst = new();
// dma_dir_x_irq_src_x_power_inst.sample();
