// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : example_soc
// Generated: 2026-06-03 09:18
// Desc     : Feature: interrupt_handling
// ============================================================================


// Feature Description: Interrupt controller — priority, masking, nesting, and source coverage
//
// Tags: interrupt, isr, priority
// Source: specs/interrupt_spec_v1.5.pdf

// Feature: interrupt_handling
// CoverGroups: priority_cg, mask_cg, nesting_cg

covergroup priority_cg @(posedge clk) iff (irq_valid);  // Interrupt priority levels
  option.goal = 100;

  priority_cp : coverpoint irq_priority {
    bins BIN_CRITICAL = {0};
    bins BIN_HIGH = {1, 2};
    bins BIN_MEDIUM = {[3:7]};
    bins BIN_LOW = {[8:15]};
    bins BIN_DEFAULT_PRIO = default;
  }

  source_cp : coverpoint irq_source {  // Interrupt source ID
    bins BIN_DMA_IRQ = {0, 1, 2, 3};
    bins BIN_UART_IRQ = {4, 5};
    bins BIN_SPI_IRQ = {6, 7};
    bins BIN_TIMER_IRQ = {8, 9, 10, 11};
    bins BIN_GPIO_IRQ = {[12:31]};
    ignore_bins BIN_RSVD = {[32:63]};
  }

  prio_x_source : cross priority_cp, source_cp {  // Priority vs source cross
  }
endgroup : priority_cg

covergroup mask_cg @(posedge clk);  // Interrupt mask register coverage
  option.goal = 100;

  mask_cp : coverpoint irq_mask {
    bins BIN_ALL_UNMASKED = {0};
    wildcard bins BIN_ALL_MASKED = {32'hFFFFFFFF};
    bins[] BIN_PARTIAL = {};  // auto
  }
endgroup : mask_cg

covergroup nesting_cg @(posedge clk) iff (isr_active);  // Nested interrupt scenarios
  option.goal = 100;

  nest_depth_cp : coverpoint isr_nest_depth {
    bins BIN_DEPTH_0 = {0};
    bins BIN_DEPTH_1 = {1};
    bins BIN_DEPTH_2 = {2};
    bins BIN_DEPTH_3_PLUS = {[3:7]};
    bins BIN_OVERFLOW = {8};
    illegal_bins BIN_ILLEGAL_DEPTH = {[9:255]};
  }

  nesting_state_cp : coverpoint isr_state {
    bins BIN_PREEMPT = (ISR_ACTIVE => ISR_PREEMPT => ISR_RESUME);
    bins BIN_LATE_ARRIVAL = (ISR_ACTIVE => ISR_PENDING);
  }
endgroup : nesting_cg

// ---------------------------------------------------------------------------
// Instantiation template (copy to your testbench/class):
// ---------------------------------------------------------------------------
// priority_cg interrupt_handling_priority_cg_inst;
// initial interrupt_handling_priority_cg_inst = new();
// // In your sample task:
// interrupt_handling_priority_cg_inst.sample();
//
// mask_cg interrupt_handling_mask_cg_inst;
// initial interrupt_handling_mask_cg_inst = new();
// // In your sample task:
// interrupt_handling_mask_cg_inst.sample();
//
// nesting_cg interrupt_handling_nesting_cg_inst;
// initial interrupt_handling_nesting_cg_inst = new();
// // In your sample task:
// interrupt_handling_nesting_cg_inst.sample();
//