// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : example_soc
// Generated: 2026-06-03 09:18
// Desc     : Feature: power_management
// ============================================================================


// Feature Description: Device power states and transitions
//
// Tags: power, clk_gate, retention
// Source: specs/power_spec_v1.0.pdf

// Feature: power_management
// CoverGroups: power_state_cg

covergroup power_state_cg @(posedge clk);  // Power state machine coverage
  option.goal = 100;

  pstate_cp : coverpoint power_state {
    bins BIN_ACTIVE = {0};
    bins BIN_IDLE = {1};
    bins BIN_SLEEP = {2};
    bins BIN_DEEP_SLEEP = {3};
    bins BIN_OFF = {4};
  }

  pstate_trans_cp : coverpoint power_state {
    bins BIN_ACTIVE_TO_IDLE = (ACTIVE => IDLE);
    bins BIN_IDLE_TO_SLEEP = (IDLE => SLEEP);
    bins BIN_SLEEP_TO_DEEP = (SLEEP => DEEP_SLEEP);
    bins BIN_WAKE_FROM_SLEEP = (SLEEP => ACTIVE), (DEEP_SLEEP => IDLE => ACTIVE);
    bins BIN_FULL_POWER_CYCLE = (ACTIVE => IDLE => SLEEP => DEEP_SLEEP => IDLE => ACTIVE);
  }
endgroup : power_state_cg

// ---------------------------------------------------------------------------
// Instantiation template (copy to your testbench/class):
// ---------------------------------------------------------------------------
// power_state_cg power_management_power_state_cg_inst;
// initial power_management_power_state_cg_inst = new();
// // In your sample task:
// power_management_power_state_cg_inst.sample();
//