// Auto-generated SystemVerilog FSM — LDO
// Generated by surrogate_framework FSMCodeGenerator

module ldo_fsm (
    input  logic clk,
    input  logic rst_n,
    input  logic HIGH_POWER_MODE,
    input  logic SREF_ADD_LDO1V2_LOAD_MPOS,
    input  logic VPWR_SEL,
    input  logic EN_LDO,
    input  logic EN_SCAN_MODE_MPOS,
    input  logic SCAN_MODE_VSUPPLY,
    output logic ready,
    output logic fault_out
);

    typedef enum logic [3:0] {
        DISABLED,
        REGULATION,
        REGULATION_2,
        REGULATION_3,
        HIGH_POWER_MODE,
        SCAN_MODE,
        REGULATION_4
    } state_t;

    state_t current_state, next_state;

    localparam real Output_Voltage_nom = 1.2;  // V
    localparam real Dropout_Voltage_nom = 0.15;  // V
    localparam real Load_Regulation_nom = 12.5;  // mV/A
    localparam real Line_Regulation_nom = 1.5;  // mV/V
    localparam real PSRR_at_1kHz_nom = 80.0;  // dB
    localparam real PSRR_at_1MHz_nom = 40.0;  // dB
    localparam real Output_Noise_RMS_nom = 15.0;  // uVrms
    localparam real Transient_Undershoot_nom = 50.0;  // mV
    localparam real Transient_Settling_nom = 2.5;  // us
    localparam real Output_Impedance_10MHz_nom = 25.0;  // mOhm
    localparam real Quiescent_Current_nom = 0.05;  // mA
    localparam real Max_Load_Current_nom = 220.0;  // mA

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            current_state <= DISABLED;
        else
            current_state <= next_state;
    end

    always_comb begin
        next_state = current_state;
        ready     = 1'b0;
        fault_out = 1'b0;

        case (current_state)
            DISABLED: begin
                if ((HIGH_POWER_MODE))
                    next_state = HIGH_POWER_MODE;
                else if ((SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION_4;
            end
            REGULATION: begin
                ready = 1'b1;
                if ((VPWR_SEL))
                    next_state = REGULATION_2;
                else if ((SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = SCAN_MODE;
            end
            REGULATION_2: begin
                ready = 1'b1;
                if ((!VPWR_SEL && !SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION;
                else if ((!EN_LDO))
                    next_state = REGULATION_3;
                else if ((SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = SCAN_MODE;
            end
            REGULATION_3: begin
                ready = 1'b1;
                if ((EN_LDO))
                    next_state = REGULATION_2;
            end
            HIGH_POWER_MODE: begin
                if ((!HIGH_POWER_MODE))
                    next_state = DISABLED;
            end
            SCAN_MODE: begin
                if ((!SREF_ADD_LDO1V2_LOAD_MPOS && !VPWR_SEL))
                    next_state = REGULATION;
                else if ((!SREF_ADD_LDO1V2_LOAD_MPOS && VPWR_SEL))
                    next_state = REGULATION_2;
            end
            REGULATION_4: begin
                ready = 1'b1;
                if ((!SREF_ADD_LDO1V2_LOAD_MPOS && !EN_SCAN_MODE_MPOS && !SCAN_MODE_VSUPPLY))
                    next_state = DISABLED;
            end
            default: next_state = DISABLED;
        endcase
    end

endmodule  // ldo_fsm