"""
fcov_forge/generators/sv_generator.py
=======================================
Generates SystemVerilog output from the FeatureModel.

Outputs:
  1. Per-feature SV files with native covergroups
  2. Feature-cross SV files with synthesized covergroups
  3. A top-level package that imports all generated coverage
  4. A testbench integration snippet
"""

from __future__ import annotations
from pathlib import Path
from datetime import datetime
from typing import Optional

from core.model import FeatureModel, Feature, CoverGroup
from core.cross_engine import CrossEngine, SynthesizedCross


# ---------------------------------------------------------------------------
# File header
# ---------------------------------------------------------------------------

def _header(project: str, description: str) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""\
// ============================================================================
// AUTO-GENERATED by FCovForge — DO NOT EDIT MANUALLY
// Project  : {project}
// Generated: {now}
// Desc     : {description}
// ============================================================================

"""


# ---------------------------------------------------------------------------
# Feature SV generator
# ---------------------------------------------------------------------------

def feature_to_sv(feature: Feature, project: str) -> str:
    """Render a Feature as a SV file (interface + covergroup declarations)."""
    lines = [_header(project, f"Feature: {feature.name}")]

    if feature.description:
        lines.append(f"// Feature Description: {feature.description}")
        lines.append(f"//")
    if feature.tags:
        lines.append(f"// Tags: {', '.join(feature.tags)}")
    if feature.source_doc:
        lines.append(f"// Source: {feature.source_doc}")
    lines.append(f"")

    lines.append(f"// Feature: {feature.name}")
    lines.append(f"// CoverGroups: {', '.join(cg.name for cg in feature.covergroups)}")
    lines.append(f"")

    for cg in feature.covergroups:
        lines.append(cg.to_sv(indent=0))
        lines.append(f"")

    # Instantiation template
    lines.append(f"// ---------------------------------------------------------------------------")
    lines.append(f"// Instantiation template (copy to your testbench/class):")
    lines.append(f"// ---------------------------------------------------------------------------")
    for cg in feature.covergroups:
        inst_name = f"{feature.name}_{cg.name}_inst"
        lines.append(f"// {cg.name} {inst_name};")
        lines.append(f"// initial {inst_name} = new();")
        lines.append(f"// // In your sample task:")
        lines.append(f"// {inst_name}.sample();")
        lines.append(f"//")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cross SV generator
# ---------------------------------------------------------------------------

def crosses_to_sv(crosses: list[SynthesizedCross], project: str) -> str:
    """Render all synthesized feature crosses to SV."""
    lines = [_header(project, "Feature-Level Cross Coverage (Synthesized)")]
    lines.append(f"// {len(crosses)} feature cross(es) defined")
    lines.append(f"")

    for sc in crosses:
        lines.append(sc.to_sv())
        lines.append(f"")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Top-level package
# ---------------------------------------------------------------------------

def top_package_sv(model: FeatureModel, include_files: list[str]) -> str:
    """Generate a SV package that `include`s all feature coverage files."""
    lines = [_header(model.project_name, "Top-Level Coverage Package")]
    lines.append(f"package {model.project_name}_fcov_pkg;")
    lines.append(f"")
    for f in include_files:
        lines.append(f'  `include "{f}"')
    lines.append(f"")
    lines.append(f"endpackage : {model.project_name}_fcov_pkg")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# UVM-style coverage collector template
# ---------------------------------------------------------------------------

def uvm_collector_sv(model: FeatureModel) -> str:
    """Generate a UVM coverage collector class skeleton."""
    pn = model.project_name
    lines = [_header(pn, "UVM Coverage Collector (skeleton)")]
    lines.append(f'`include "uvm_macros.svh"')
    lines.append(f"import uvm_pkg::*;")
    lines.append(f"import {pn}_fcov_pkg::*;")
    lines.append(f"")
    lines.append(f"class {pn}_coverage extends uvm_subscriber #(/* transaction type */);")
    lines.append(f"  `uvm_component_utils({pn}_coverage)")
    lines.append(f"")

    # Declare one handle per covergroup across all features
    for feat in model.features:
        for cg in feat.covergroups:
            inst = f"{feat.name}_{cg.name}_cov"
            lines.append(f"  {cg.name} {inst};")

    lines.append(f"")
    lines.append(f"  function new(string name, uvm_component parent);")
    lines.append(f"    super.new(name, parent);")
    lines.append(f"  endfunction")
    lines.append(f"")
    lines.append(f"  function void build_phase(uvm_phase phase);")
    lines.append(f"    super.build_phase(phase);")
    for feat in model.features:
        for cg in feat.covergroups:
            inst = f"{feat.name}_{cg.name}_cov"
            lines.append(f"    {inst} = new();")
    lines.append(f"  endfunction")
    lines.append(f"")
    lines.append(f"  function void write(/* transaction type */ t);")
    lines.append(f"    // TODO: unpack transaction fields into signals")
    for feat in model.features:
        for cg in feat.covergroups:
            inst = f"{feat.name}_{cg.name}_cov"
            lines.append(f"    {inst}.sample();")
    lines.append(f"  endfunction")
    lines.append(f"")
    lines.append(f"endclass : {pn}_coverage")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_all(model: FeatureModel, output_dir: str | Path) -> dict[str, Path]:
    """
    Generate all SV output files for a FeatureModel.

    Returns a dict of {description: path} for all generated files.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = {}

    # Per-feature files
    feature_files = []
    for feature in model.features:
        fname = f"{feature.name}_coverage.sv"
        path = output_dir / fname
        path.write_text(feature_to_sv(feature, model.project_name))
        generated[f"feature:{feature.name}"] = path
        feature_files.append(fname)

    # Feature cross file
    engine = CrossEngine(model)
    errors = engine.validate()
    if errors:
        print("[CrossEngine] Validation warnings:")
        for e in errors:
            print(f"  ⚠ {e}")

    if model.feature_crosses:
        crosses = engine.synthesize_all()
        cross_fname = f"{model.project_name}_feature_crosses.sv"
        cross_path = output_dir / cross_fname
        cross_path.write_text(crosses_to_sv(crosses, model.project_name))
        generated["feature_crosses"] = cross_path
        feature_files.append(cross_fname)

    # Top package
    pkg_path = output_dir / f"{model.project_name}_fcov_pkg.sv"
    pkg_path.write_text(top_package_sv(model, feature_files))
    generated["package"] = pkg_path

    # UVM collector
    uvm_path = output_dir / f"{model.project_name}_coverage.sv"
    uvm_path.write_text(uvm_collector_sv(model))
    generated["uvm_collector"] = uvm_path

    return generated
