// Auto-generated SystemVerilog FSM — LDO
// Generated by surrogate_framework FSMCodeGenerator

module ldo_fsm (
    input  logic clk,
    input  logic rst_n,
    input  logic SREF_LDO1V2_LP_TB_ICONST_75A_0_,
    input  logic SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__0_,
    input  logic SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__1_,
    input  logic SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__2_,
    input  logic SREF_LDO1V2_LP_TB_X_DUT_ICONST_75A_0_,
    output logic ready,
    output logic fault_out
);

    typedef enum logic [3:0] {
        REGULATION,
        UVLO,
        STARTUP,
        REGULATION_2,
        REGULATION_3,
        REGULATION_4,
        OVERRIDE
    } state_t;

    state_t current_state, next_state;

    localparam real Output_Voltage_nom = 1.2;  // V
    localparam real Dropout_Voltage_nom = 0.15;  // V
    localparam real Load_Regulation_nom = 12.5;  // mV/A
    localparam real Line_Regulation_nom = 1.5;  // mV/V
    localparam real PSRR_at_1kHz_nom = 80.0;  // dB
    localparam real PSRR_at_1MHz_nom = 40.0;  // dB
    localparam real Output_Noise_RMS_nom = 15.0;  // uVrms
    localparam real Transient_Undershoot_nom = 50.0;  // mV
    localparam real Transient_Settling_nom = 2.5;  // us
    localparam real Output_Impedance_10MHz_nom = 25.0;  // mOhm
    localparam real Quiescent_Current_nom = 0.05;  // mA
    localparam real Max_Load_Current_nom = 220.0;  // mA

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            current_state <= REGULATION;
        else
            current_state <= next_state;
    end

    always_comb begin
        next_state = current_state;
        ready     = 1'b0;
        fault_out = 1'b0;

        case (current_state)
            REGULATION: begin
                ready = 1'b1;
                if ((SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__1_))
                    next_state = UVLO;
                else if ((SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__2_))
                    next_state = REGULATION_3;
            end
            UVLO: begin
                if ((SREF_LDO1V2_LP_TB_ICONST_75A_0_ && SREF_LDO1V2_LP_TB_X_DUT_ICONST_75A_0_))
                    next_state = STARTUP;
            end
            STARTUP: begin
                if ((!SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__1_))
                    next_state = REGULATION_2;
            end
            REGULATION_2: begin
                ready = 1'b1;
                if ((!SREF_LDO1V2_LP_TB_ICONST_75A_0_ && !SREF_LDO1V2_LP_TB_X_DUT_ICONST_75A_0_))
                    next_state = REGULATION;
            end
            REGULATION_3: begin
                ready = 1'b1;
                if ((SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__0_ && SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__1_))
                    next_state = REGULATION_4;
            end
            REGULATION_4: begin
                ready = 1'b1;
                if ((SREF_LDO1V2_LP_TB_ICONST_75A_0_ && SREF_LDO1V2_LP_TB_X_DUT_ICONST_75A_0_))
                    next_state = OVERRIDE;
            end
            OVERRIDE: begin
                if ((!SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__0_ && !SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__1_ && !SREF_LDO1V2_LP_TB_X_DUT_IBIAS_SNK_25nA__2_))
                    next_state = REGULATION_2;
            end
            default: next_state = REGULATION;
        endcase
    end

endmodule  // ldo_fsm