// Auto-generated SystemVerilog FSM — LDO
// Generated by surrogate_framework FSMCodeGenerator

module ldo_fsm (
    input  logic clk,
    input  logic rst_n,
    input  logic EN_LDO,
    input  logic EN_SCAN_MODE_MPOS,
    input  logic FS_V_SUPPLY_TO_MOST_POS,
    input  logic HIGH_POWER_MODE,
    input  logic PAD_VDD1V2_SEL,
    input  logic SCAN_MODE_VSUPPLY,
    input  logic SREF_ADD_LDO1V2_LOAD_MPOS,
    input  logic UVLO_GD_OR_OVERRIDE_MPOS,
    input  logic VPWR_SEL,
    output logic ready,
    output logic fault_out
);

    typedef enum logic [4:0] {
        DISABLED,
        DISABLED_2,
        REGULATION,
        REGULATION_2,
        REGULATION_3,
        REGULATION_4,
        DISABLED_3,
        REGULATION_5,
        DISABLED_4,
        DISABLED_5,
        DISABLED_6,
        REGULATION_6,
        REGULATION_7,
        DISABLED_7,
        REGULATION_8,
        REGULATION_9,
        REGULATION_10
    } state_t;

    state_t current_state, next_state;

    localparam real Output_Voltage_nom = 1.2;  // V
    localparam real Dropout_Voltage_nom = 0.15;  // V
    localparam real Load_Regulation_nom = 12.5;  // mV/A
    localparam real Line_Regulation_nom = 1.5;  // mV/V
    localparam real PSRR_at_1kHz_nom = 80.0;  // dB
    localparam real PSRR_at_1MHz_nom = 40.0;  // dB
    localparam real Output_Noise_RMS_nom = 15.0;  // uVrms
    localparam real Transient_Undershoot_nom = 50.0;  // mV
    localparam real Transient_Settling_nom = 2.5;  // us
    localparam real Output_Impedance_10MHz_nom = 25.0;  // mOhm
    localparam real Quiescent_Current_nom = 0.05;  // mA
    localparam real Max_Load_Current_nom = 220.0;  // mA

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            current_state <= DISABLED;
        else
            current_state <= next_state;
    end

    always_comb begin
        next_state = current_state;
        ready     = 1'b0;
        fault_out = 1'b0;

        case (current_state)
            DISABLED: begin
                if ((VPWR_SEL))
                    next_state = DISABLED_2;
                else if ((EN_LDO))
                    next_state = REGULATION_2;
            end
            DISABLED_2: begin
                if ((EN_LDO && EN_SCAN_MODE_MPOS && HIGH_POWER_MODE && PAD_VDD1V2_SEL && SCAN_MODE_VSUPPLY && SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION_10;
                else if ((EN_LDO && EN_SCAN_MODE_MPOS && HIGH_POWER_MODE && SCAN_MODE_VSUPPLY))
                    next_state = REGULATION_9;
                else if ((EN_LDO && EN_SCAN_MODE_MPOS && SCAN_MODE_VSUPPLY))
                    next_state = REGULATION_4;
                else if ((EN_LDO && HIGH_POWER_MODE && SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION_7;
                else if ((EN_LDO && HIGH_POWER_MODE && PAD_VDD1V2_SEL))
                    next_state = REGULATION_8;
                else if ((EN_LDO && PAD_VDD1V2_SEL))
                    next_state = REGULATION_5;
                else if ((PAD_VDD1V2_SEL && UVLO_GD_OR_OVERRIDE_MPOS))
                    next_state = DISABLED_5;
                else if ((EN_SCAN_MODE_MPOS && SCAN_MODE_VSUPPLY))
                    next_state = DISABLED_6;
                else if ((EN_LDO && HIGH_POWER_MODE))
                    next_state = REGULATION_6;
                else if ((EN_LDO))
                    next_state = REGULATION;
                else if ((PAD_VDD1V2_SEL))
                    next_state = DISABLED_4;
            end
            REGULATION: begin
                ready = 1'b1;
                if ((EN_SCAN_MODE_MPOS && SCAN_MODE_VSUPPLY))
                    next_state = REGULATION_4;
                else if ((!EN_LDO))
                    next_state = DISABLED_2;
                else if ((!VPWR_SEL))
                    next_state = REGULATION_2;
                else if ((SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION_3;
                else if ((PAD_VDD1V2_SEL))
                    next_state = REGULATION_5;
                else if ((HIGH_POWER_MODE))
                    next_state = REGULATION_6;
            end
            REGULATION_2: begin
                ready = 1'b1;
                if ((VPWR_SEL))
                    next_state = REGULATION;
            end
            REGULATION_3: begin
                ready = 1'b1;
                if ((!EN_LDO))
                    next_state = DISABLED_3;
            end
            REGULATION_4: begin
                ready = 1'b1;
                if ((!EN_LDO))
                    next_state = DISABLED_6;
            end
            DISABLED_3: begin
                if ((EN_LDO && !SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION;
                else if ((EN_LDO))
                    next_state = REGULATION_3;
            end
            REGULATION_5: begin
                ready = 1'b1;
                if ((!EN_LDO))
                    next_state = DISABLED_4;
                else if ((!PAD_VDD1V2_SEL))
                    next_state = REGULATION;
            end
            DISABLED_4: begin
                if ((!PAD_VDD1V2_SEL))
                    next_state = DISABLED_2;
                else if ((UVLO_GD_OR_OVERRIDE_MPOS))
                    next_state = DISABLED_5;
                else if ((EN_LDO))
                    next_state = REGULATION_5;
            end
            DISABLED_5: begin
                if ((!UVLO_GD_OR_OVERRIDE_MPOS))
                    next_state = DISABLED_4;
            end
            DISABLED_6: begin
            end
            REGULATION_6: begin
                ready = 1'b1;
                if ((!HIGH_POWER_MODE))
                    next_state = REGULATION;
                else if ((SREF_ADD_LDO1V2_LOAD_MPOS))
                    next_state = REGULATION_7;
            end
            REGULATION_7: begin
                ready = 1'b1;
            end
            DISABLED_7: begin
                if ((VPWR_SEL))
                    next_state = DISABLED_3;
            end
            REGULATION_8: begin
                ready = 1'b1;
            end
            REGULATION_9: begin
                ready = 1'b1;
            end
            REGULATION_10: begin
                ready = 1'b1;
            end
            default: next_state = DISABLED;
        endcase
    end

endmodule  // ldo_fsm